---
title: "eleanortestfile"
author: "E.M.Thomas"
date: "2023-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(here)
library(sf)
library(tidyverse)
library(terra) ### raster data functionality
library(tmap)
library(rgdal)
library(stars)
library(sp)
library(terra)
```



```{r}
hawaii_parks_sf <- read_sf(here("nlcd_data","hawaii_2001", "parks_state","parks_state.shp"))

# Read in shapefile
hawaii_parks_vector <- read_sf(here("nlcd_data","hawaii_2001", "parks_state","parks_state.shp")) 

# Filter for specific national park 
ak_park <- hawaii_parks_vector %>% 
   filter(NAME == "AHUPUAA O KAHANA STATE PARK") #this turns ak_park into an sp file because we used the filter function

```


```{r}
# Define region of interest vector 
roi_sf <- ak_park

roi_sf <- hawaii_parks_sf

class(hawaii_parks_sf)
class(roi_sf)

# Project vector file to match raster file
roi_sf_proj <- st_transform(roi_sf, crs(lc_rast))

# Crop raster 
lc_roi_rast <- crop(lc_rast, roi_sf_proj)

# Mask raster with vector file
lc_roi_masked_rast <- mask(lc_roi_rast, roi_sf_proj)
plot(lc_roi_masked_rast)
```


