---
title: "Testing"
author: "E.M.Thomas"
date: "2023-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(here)
library(sf)
library(tidyverse)
library(terra) ### raster data functionality
library(tmap)
library(rgdal)
library(stars)
```


```{r}
adf1 <- raster(here("nlcd_data/ny_nlcd2019/w001001.adf"))
plot(adf1)

metadata <- XML::xmlToDataFrame(here("nlcd_data/ny_nlcd2019/metadata.xml"))

nypa_facilties <- read_sf(here("nypa_landholdings/NYPA_Facilities.shp")) %>% 
  janitor::clean_names()

plot(nypa_facilties$geometry)
              
```
```{r}
st_crs(nypa_facilties) <- 9001


st_crs(adf1)
st_crs(nypa_facilties)
 


```

```{r}
ggplot() +
  geom_sf(data = as.data.frame(adf1)) + 
  geom_sf(data = as.data.frame(nypa_facilties)) +
  theme_void()
```


```{r}
land_cover_file <- here("nlcd_us", "nlcd_2019_land_cover_l48_20210604.img")

lc_rast <- terra::rast(land_cover_file)
lc_rast
```

```{r}
lc_1_rast <- lc_rast[[1]]
plot(lc_1_rast, main = 'US Landcover Map', 
     col = hcl.colors(20), axes = FALSE)
```

```{r}
arturo_clip_file <- here("nlcd_data", "ny_nlcd2019", "prj.adf")

aclip_rast <- terra::rast(arturo_clip_file)
aclip_rast
```


```{r}
aclip_1_rast <- aclip_rast[[1]]
plot(aclip_1_rast, main = 'Arturo NY Clip', 
     col = hcl.colors(20), axes = FALSE)
```


```{r}
cclip_file <- here("nlcd_us", "clipped_NY.tif")

cclip_rast <- terra::rast(cclip_file)
cclip_rast
```


```{r}
cclip_1_rast <- cclip_rast[[1]]
plot(cclip_1_rast, main = 'Chloe Clip Map', 
     col = hcl.colors(20), axes = FALSE)
```

  
```{r}
ny_vector <- read_sf(here("nlcd_us","NY_state.gpkg")) %>% 
  select(geom)
plot(ny_vector)
```

###attempting to rasterize NY vector 
```{r}
ny_rast <- st_rasterize(ny_vector, lc_rast)
```

```{r}
ny_rast_2 <- rasterize(ny_vector, aclip_rast)
```


```{r}
plot(ny_rast_2)
```




### making lc_rast a df
```{r}
us_df <- as.data.frame(lc_1_rast, xy = TRUE)
```

## trying to crop lc by ny 
```{r}
landtype_crop1 <- crop(lc_rast, ny_vector)

plot(landtype_crop, main = "Cropped lidar")
```

## trying to crop lc_rast by ny_vector
```{r}
landtype_crop <- crop(lc_rast, ny_rast_2)

plot(landtype_crop, main = "Cropped lidar")

```


```{r}
ggplot() +
  geom_raster(data = lc_1_rast, aes(x = x, y = y)) + 
  geom_sf(data = ny_vector, color = "blue", fill = NA) +
  coord_sf()
```

###dont run this 
```{r}
#plot_2<- plot(lc_1_rast, main = 'US Landcover Map', 
     #col = hcl.colors(20), axes = FALSE,
    # ny_vector, add = TRUE)
```

# add shapefile on top of the existing raster
plot(crop_extent, add = TRUE)











