---
title: "carbonstocktesting"
author: "C. E. Mori"
date: "2023-03-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(here)
library(janitor)
library(tidyverse)

ratio_carbon_tph <- readxl::read_xlsx(here("carbon_stock_cfs/carbon_storage_ton_C_per_hectare.xlsx")) %>% 
  clean_names() %>% 
  select(class:soc) %>% 
  pivot_longer(cols = above:soc, names_to = "compartment", values_to = "ton_c_per_hectare")

### For app, the required input is a table total_area_per_class with class and total area! Below is just a test df.
test_class_areas <- readxl::read_xlsx(here("carbon_stock_cfs/test_areas.xlsx")) %>% 
  clean_names()

test_total_carbon <- merge(test_class_areas, ratio_carbon_tph, by = "class") %>% 
  mutate(total_carbon = area * ton_c_per_hectare) %>% 
  mutate(class_factor = as.factor(class))
```

```{r}
test_plot <- ggplot() +
  geom_col(data = test_total_carbon, mapping = aes(x = class_factor, y = total_carbon, fill = compartment)) +
  scale_fill_manual(values = c("darkseagreen1", "slateblue1", "tan1", "lightgoldenrod1", "thistle1")) +
  theme_dark()

test_plot
```

